title: OpenHands Backend + Novel Writing AI
emoji: 🎭
colorFrom: purple
colorTo: pink
sdk: docker
pinned: false
license: mit
app_port: 7860
tags:
  - openai
  - chatbot
  - api
  - backend
  - novel-writing
  - indonesian
  - creative-writing
  - openrouter
models:
  - openai/gpt-4o-mini
  - anthropic/claude-3-haiku-20240307
  - anthropic/claude-3-opus-20240229